services:
  frontend:
    image: hayo87/automata-explorer-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
      image: hayo87/automata-explorer-backend:latest
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
