version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_BASE_URL=http://backend:8080/api 

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
